version: '1'

services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}    
    depends_on: 
      postgres
  postgres: 
    build: ./DockerDB/
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}