version: '3.3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks: 
      - net
  postgres:
    build: ./DockerDB/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks: 
      - net
networks: 
  net:
    driver: bridge 
