version: '3.4'

services:
  rsrestservicestarter:
    image: rsrestservicestarter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
