version: '3.3'
services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_HOST: postgres
      AUTH_KEY: ${AUTH_KEY}
    depends_on:
      - postgres
    networks: 
      - net
    restart: always
    volumes:
      - ./log:/usr/src/app/log
  postgres:
    build: ./DockerDB/
    ports:
      - ${POSTGRES_PORT_SERV}:${POSTGRES_PORT}
    volumes: 
      - postgre_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      PGDATA: /var/lib/postgresql/data
    restart: always
    
    networks: 
      - net
networks: 
  net:
    driver: bridge 
volumes: 
  postgre_db:
